windowManager:
    MenuScreen:
    ProfileScreen:
    SignupScreen:
    UploadScreen:
    Exercise:
    Yoga:
    Entertainment:
    UserProfile:
    P:
    Y1:
    Y2:
    Y3:
    Y4:
    E1:
    E2:
    E3:
    E4:

<MenuScreen>:
    name: 'menu'

    Screen:
        #:set w 400
        #:set h 400
        canvas.before:
            Rectangle:
                pos: self.pos
                source: 'Capture.png'
                pos:(40,200)
                size:(w,h)
        BoxLayout:
            orientation: 'vertical'
            MDToolbar:
                title: 'Demo Application'
                halign:'center'
                elevation:10
            MDLabel:
                text:'Health App'
                halign:'center'
                theme_text_color:'Custom'
                text_color:(1, 0, 0)
                font_style:'H4'
                bold:True
        MDRectangleFlatButton:
            text:'Login'
            pos_hint:{'center_x': 0.4, 'center_y': 0.19}
            text_color:(1, 0, 0)
            on_press:
                root.manager.current = 'profile'
                root.manager.transition.direction = 'up'
        MDRectangleFlatButton:
            text:'Sign-up'
            pos_hint:{'center_x': 0.6, 'center_y': 0.19}
            text_color:(1, 0, 0)
            on_press:
                root.manager.current = 'sig'
                root.manager.transition.direction = 'up'

        MDFloatingActionButton
            icon:'instagram'
        MDFloatingActionButton
            icon:'youtube'
            pos_hint:{'x': 0.42, 'y': 0}
        MDFloatingActionButton
            icon:'gmail'
            pos_hint:{'x': .88, 'y': 0}

<ProfileScreen>:
    name: 'profile'
    email : email
    pwd : pwd
    Screen:
        BoxLayout:
            orientation: 'vertical'
            MDToolbar:
                title: 'Demo Application'
                halign:'center'
                elevation:10
            ScrollView:
        MDFloatingActionButton
            icon:'instagram'
        MDFloatingActionButton
            icon:'youtube'
            pos_hint:{'x': 0.42, 'y': 0}
        MDFloatingActionButton
            icon:'gmail'
            pos_hint:{'x': .88, 'y': 0}
        MDRectangleFlatButton:
            text: 'Back'
            pos_hint: {'center_x':0.5,'center_y':0.2}
            on_press: root.manager.current = 'menu'
        MDTextField:
            id:email
            hint_text:"Enter Email-ID"
            #helper_text:"or click on forgot username"
            helper_text_mode: "on_focus" #persistent
            icon_right:"basketball"
            icon_right_color: app.theme_cls.primary_color #(1,0,0)
            pos_hint:{'center_x':0.5,'center_y':0.6}
            size_hint_x:None  #size_hint:(0.5,0.1)
            width:300
        MDTextField:
            id:pwd
            hint_text:"Enter Password"
            #helper_text:"or click on forgot username"
            helper_text_mode: "on_focus" #persistent
            icon_right:"basketball"
            icon_right_color: app.theme_cls.primary_color #(1,0,0)
            pos_hint:{'center_x':0.5,'center_y':0.5}
            size_hint_x:None  #size_hint:(0.5,0.1)
            width:300
        MDRectangleFlatButton:
            text:'Enter'
            pos_hint:{'center_x':0.5,'center_y':0.4}
            on_press:
                # root.validate()
                root.manager.current = 'upload'
                root.manager.transition.direction = 'right'
<SignupScreen>:
    name:'sig'
    name2 : name2
    email : email
    pwd : pwd
    Screen:
        BoxLayout:
            orientation: 'vertical'
            MDToolbar:
                title: 'Demo Application'
                halign:'center'
                elevation:10
            ScrollView:
        MDFloatingActionButton
            icon:'instagram'
        MDFloatingActionButton
            icon:'youtube'
            pos_hint:{'x': 0.42, 'y': 0}
        MDFloatingActionButton
            icon:'gmail'
            pos_hint:{'x': .88, 'y': 0}
        MDRectangleFlatButton:
            text: 'Back'
            pos_hint: {'center_x':0.5,'center_y':0.2}
            on_press: root.manager.current = 'menu'
        MDTextField:
            id:name2
            hint_text:"Enter Username"
            #helper_text:"or click on forgot username"
            helper_text_mode: "on_focus" #persistent
            icon_right:"basketball"
            icon_right_color: app.theme_cls.primary_color #(1,0,0)
            pos_hint:{'center_x':0.5,'center_y':0.7}
            size_hint_x:None  #size_hint:(0.5,0.1)
            width:300
        MDTextField:
            id:email
            hint_text:"Enter Email-ID"
            #helper_text:"or click on forgot username"
            helper_text_mode: "on_focus" #persistent
            icon_right:"basketball"
            icon_right_color: app.theme_cls.primary_color #(1,0,0)
            pos_hint:{'center_x':0.5,'center_y':0.6}
            size_hint_x:None  #size_hint:(0.5,0.1)
            width:300
        MDTextField:
            id:pwd
            hint_text:"Enter Password"
            #helper_text:"or click on forgot username"
            helper_text_mode: "on_focus" #persistent
            icon_right:"basketball"
            icon_right_color: app.theme_cls.primary_color #(1,0,0)
            pos_hint:{'center_x':0.5,'center_y':0.5}
            size_hint_x:None  #size_hint:(0.5,0.1)
            width:300
        MDRectangleFlatButton:
            text:'Enter'
            pos_hint:{'center_x':0.5,'center_y':0.4}
            on_press:
                root.signupbtn()
                root.manager.transition.direction = 'right'

<UploadScreen>:
    name: 'upload'
    Screen:
        MDNavigationLayout:
            ScreenManager:
                Screen:
                    BoxLayout:
                        orientation: 'vertical'

                        MDToolbar:
                            title: 'Demo Application'
                            elevation: 10
                            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]

                        OneLineIconListItem:
                            text:'          ENTERTAINMENT'
                            font_style:'Subtitle1'
                            bold:'True'
                            IconLeftWidget:
                                icon:'movie'
                                on_press:
                                    root.manager.current = 'ent'
                                    root.manager.transition.direction = 'down'
                        Carousel:
                            direction:'right'
                            Image:
                                source:'q1.jpg'
                            Image:
                                source:'q2.jpg'
                            Image:
                                source:'q3.jpg'
                            Image:
                                source:'q4.jpg'

                        OneLineIconListItem:
                            text:'          EXERCISE'
                            font_style:'Subtitle1'
                            bold:'True'
                            IconLeftWidget:
                                icon:'jump-rope'
                                on_press:
                                    root.manager.current = 'exe'
                                    root.manager.transition.direction = 'left'

                        ScrollView:
                            GridLayout:
                                rows:2
                                cols:2
                                Image:
                                    source:'ex1.jpeg'
                                Image:
                                    source:'ex2.jpeg'
                                Image:
                                    source:'ex3.jpeg'
                                Image:
                                    source:'ex4.jpeg'
                        OneLineIconListItem:
                            text:'          YOGA'
                            font_style:'Subtitle1'
                            bold:'True'
                            IconLeftWidget:
                                icon:'yoga'
                                on_press:
                                    root.manager.current = 'yog'
                                    root.manager.transition.direction = 'up'
                        ScrollView:
                            GridLayout:
                                rows:2
                                cols:2
                                Image:
                                    source:'1.jpg'
                                Image:
                                    source:'5.JPG'
                                Image:
                                    source:'4.JPG'
                                Image:
                                    source:'8.JPG'
                        OneLineIconListItem:
                            text:'          SHOPPING'
                            font_style:'Subtitle1'
                            bold:'True'
                            IconLeftWidget:
                                icon:'shopping'
                                on_press:
                                    import webbrowser
                                    webbrowser.open("https://www.flipkart.com/search?q=gym+equipments+for+home&sid=qoc%2Camf%2Cvh3&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_na&as-pos=2&as-type=RECENT&suggestionId=gym+equipments+for+home%7CFitness+Kits&requestId=a61b74c7-39fb-47d9-82e0-173599ee9fcf&as-backfill=on")

                        Carousel:
                            direction:'right'
                            Image:
                                source:'g2.jpg'
                            Image:
                                source:'g1.jpg'
                            Image:
                                source:'g3.webp'
                            Image:
                                source:'g4.jpg'
                    MDFloatingActionButton
                        icon:'google-home'
                        pos_hint:{'x': .88, 'y': 0}
                        on_press:
                            root.manager.current = 'upload'












                        Widget:
                        ScrollView:

            MDNavigationDrawer:
                id: nav_drawer
                BoxLayout:
                    orientation:'vertical'
                    spacing:'4dp'
                    padding:'1dp'
                    Image:
                        source:'VISU UTKARSH.jpg'
                    MDLabel:
                        text:'                    VISU UTKARSH'
                        bold:'True'
                        font_style:'H6'
                        size_hint_y:None
                        height:self.texture_size[1]
                    MDLabel:
                        text:'                                visutkarsh2000@gamil.com'
                        font_style:'Caption'
                        size_hint_y:None
                        height:self.texture_size[1]
                    ScrollView:
                        MDList:
                            OneLineIconListItem:
                                text:'Entertainment'
                                IconLeftWidget:
                                    icon:'movie'
                                    on_press:
                                        root.manager.current = 'ent'
                                        root.manager.transition.direction = 'down'
                            OneLineIconListItem:
                                text:'Exercise'
                                IconLeftWidget:
                                    icon:'jump-rope'
                                    on_press:
                                        root.manager.current = 'exe'
                                        root.manager.transition.direction = 'up'
                            OneLineIconListItem:
                                text:'Yoga'
                                IconLeftWidget:
                                    icon:'yoga'
                                    on_press:
                                        root.manager.current = 'yog'
                                        root.manager.transition.direction = 'up'
                            OneLineIconListItem:
                                text:'Profile'
                                IconLeftWidget:
                                    icon:'face-profile'
                                    on_press:
                                        root.manager.current = 'userp'
                                        root.manager.transition.direction = 'right'
                            OneLineIconListItem:
                                text:'Logout'
                                IconLeftWidget:
                                    icon:'logout'
                                    on_press:
                                        root.manager.current = 'menu'
                                        root.manager.transition.direction = 'right'

<Exercise>:
    name:'exe'
    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: 'EXERCISE'
                        halign:'center'
                        right_action_items:[['keyboard-backspace', lambda x: setattr(root.manager, 'current', 'upload')]]
                        left_action_items:[['jump-rope']]
                        elevation:10
                    OneLineIconListItem:
                        text:'          CROSS BAR'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        source:'crossbar.gif'
                    OneLineIconListItem:
                        text:'          COBRA POSITION'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        id:gif
                        source:'cobra.gif'
                    OneLineIconListItem:
                        text:'          WIDE ARM PUSH-UP'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        source:'widearm.gif'
                    OneLineIconListItem:
                        text:'          PUSH-UP'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        source:'KTnX664Lc.gif'
                    ScrollView:
                MDFloatingActionButton
                    id : c1
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.72}
                    on_press:
                        root.count1()
                        # import webbrowser
                        # webbrowser.open("shorturl.at/anuDG=on")

                MDFloatingActionButton
                    id:c2
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.52}
                    on_press:
                        root.count2()
                        # import webbrowser
                        # webbrowser.open("shorturl.at/uAR37=on")
                MDFloatingActionButton
                    id:c3
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.32}
                    on_press: gif.anim_delay = 0.10
                    on_press: gif._coreimage.anim_reset(True)
                    on_press:
                        root.count3()
                        # import webbrowser
                        # webbrowser.open("shorturl.at/dvHIL=on")
                MDFloatingActionButton
                    id:c4
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.12}
                    on_press:
                        root.count4()
                        # import webbrowser
                        # webbrowser.open("shorturl.at/evzIK=on")
                MDFloatingActionButton
                    icon:'google-home'
                    pos_hint:{'x': .88, 'y': 0}
                    on_press:
                        root.manager.current = 'upload'
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':0.88, 'y': 0.72}
                    on_press:
                        root.info1()
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':.88, 'y': .52}
                    on_press:
                        root.info2()
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':.88, 'y': .32}
                    on_press:
                        root.info3()
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':.88, 'y': .12}
                    on_press:
                        root.info4()
<Yoga>:
    name:'yog'

    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: 'YOGA'
                        halign:'center'
                        right_action_items:[['keyboard-backspace', lambda x: setattr(root.manager, 'current', 'upload')]]
                        left_action_items:[['yoga']]
                        elevation:10
                    OneLineIconListItem:
                        text:'          SURYA NAMSKAR'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        source:'surya.gif'
                    OneLineIconListItem:
                        text:'           MARJARYASANA'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        source:'cat.gif'
                    OneLineIconListItem:
                        text:'          VIRABHADRASANA'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        source:'virabhadrasana.gif'
                    OneLineIconListItem:
                        text:'          ANULOM VILOM'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'google-play'
                    Image:
                        source:'anulom vilom.gif'
                    ScrollView:

                MDFloatingActionButton
                    id : c1
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.72}
                    on_press:
                        root.count1()
                        # import webbrowser
                        # webbrowser.open("shorturl.at/sxGLM=on")


                MDFloatingActionButton
                    id:c2
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.52}
                    on_press:
                        root.count2()
                        import webbrowser
                        webbrowser.open("shorturl.at/bgrDZ=on")
                MDFloatingActionButton
                    id:c3
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.32}
                    on_press:
                        root.count3()
                        # import webbrowser
                        # webbrowser.open("shorturl.at/qDVZ8=on")
                MDFloatingActionButton
                    id:c4
                    icon:'google-play'
                    pos_hint:{'x':0.32, 'y': 0.12}
                    on_press:
                        root.count4()
                        # import webbrowser
                        # webbrowser.open("shorturl.at/gjpvF=on")
                MDFloatingActionButton
                    icon:'google-home'
                    pos_hint:{'x': .88, 'y': 0}
                    on_press:
                        root.manager.current = 'upload'
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':0.88, 'y': 0.72}
                    on_press:
                        root.info1()
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':.88, 'y': .52}
                    on_press:
                        root.info2()
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':.88, 'y': .32}
                    on_press:
                        root.info3()
                MDFloatingActionButton
                    icon:'monitor'
                    pos_hint:{'x':.88, 'y': .12}
                    on_press:
                        root.info4()

<Entertainment>:
    name:'ent'
    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: 'ENTERTAINMENT'
                        halign:'center'
                        right_action_items:[['keyboard-backspace', lambda x: setattr(root.manager, 'current', 'upload')]]
                        left_action_items:[['movie']]
                        elevation:10
                    OneLineIconListItem:
                        text:'          MATRIX 2021'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'magnet-on'
                    Carousel:
                        direction:'right'
                        Image:
                            source:'q1.jpg'
                        Image:
                            source:'q2.jpg'
                        Image:
                            source:'q3.jpg'
                        Image:
                            source:'q4.jpg'

                    OneLineIconListItem:
                        text:'          VIKINGS VALHALLA 2022'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'litecoin'

                    Carousel:
                        direction:'right'
                        Image:
                            source:'q2.jpg'
                        Image:
                            source:'q3.jpg'
                        Image:
                            source:'q4.jpg'
                        Image:
                            source:'q1.jpg'

                    OneLineIconListItem:
                        text:'          LOVE HOSTEL 2022'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'pistol'
                    Carousel:
                        direction:'right'
                        Image:
                            source:'q3.jpg'
                        Image:
                            source:'q4.jpg'
                        Image:
                            source:'q1.jpg'
                        Image:
                            source:'q2.jpg'

                    OneLineIconListItem:
                        text:'          RIM OF THE WORLD 2019'
                        font_style:'Subtitle1'
                        bold:'True'
                        IconLeftWidget:
                            icon:'chemical-weapon'
                    Carousel:
                        direction:'right'
                        Image:
                            source:'q4.jpg'
                        Image:
                            source:'q1.jpg'
                        Image:
                            source:'q2.jpg'
                        Image:
                            source:'q3.jpg'

                    ScrollView:
                MDFloatingActionButton
                    icon:'google-play'
                    pos_hint:{'x':0.28, 'y': 0.72}
                    on_press:
                        import webbrowser
                        webbrowser.open("https://meet.google.com/=on")

                MDFloatingActionButton
                    icon:'google-play'
                    pos_hint:{'x':0.28, 'y': 0.52}
                    on_press:
                        import webbrowser
                        webbrowser.open("https://meet.google.com/=on")
                MDFloatingActionButton
                    icon:'google-play'
                    pos_hint:{'x':0.28, 'y': 0.32}
                    on_press:
                        import webbrowser
                        webbrowser.open("https://meet.google.com/=on")
                MDFloatingActionButton
                    icon:'google-play'
                    pos_hint:{'x':0.28, 'y': 0.12}
                    on_press:
                        import webbrowser
                        webbrowser.open("https://meet.google.com/?authuser=0=on")
                MDFloatingActionButton
                    icon:'google-home'
                    pos_hint:{'x': .88, 'y': 0}
                    on_press:
                        root.manager.current = 'upload'

<UserProfile>:
    name:'userp'
    Screen:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    MDToolbar:
                        title: 'PROFILE'
                        halign:'center'
                        right_action_items:[['keyboard-backspace', lambda x: setattr(root.manager, 'current', 'upload')]]
                        left_action_items:[['face-profile']]
                        elevation:10
                    Image:
                        source:'VISU UTKARSH.jpg'
                    ScrollView:
                    GridLayout:
                        rows:3
                        cols:2
                        MDLabel:
                            text:'              NAME'
                            bold:'True'
                            font_style:'Subtitle1'
                        MDLabel:
                            text:'VISU UTKARSH'
                            bold:'True'
                            font_style:'Subtitle1'
                        MDLabel:
                            text:'              EMAIL-ID'
                            bold:'True'
                            font_style:'Subtitle1'
                        MDLabel:
                            text:'visutkarsh2000@gmail.com'
                            bold:'True'
                            font_style:'Subtitle1'
                        MDLabel:
                            text:'              COIN'
                            bold:'True'
                            font_style:'Subtitle1'
                        MDLabel:
                            text:'100'
                            bold:'True'
                            font_style:'Subtitle1'
                    ScrollView:
                MDFloatingActionButton
                    icon:'google-home'
                    pos_hint:{'x': .88, 'y': 0}
                    on_press:
                        root.manager.current = 'upload'



<P>:
    Label:
        text : "Please enter valid information"
        size_hint : 0.2, 0.1
        pos_hint : {"x" : 0.3, "top" : 0.8}
<Y1>:
    Label:
        text: "SURYA NAMSKAR"
<Y2>:
    Label:
        text: "MARJARYASANA"
<Y3>:
    Label:
        text: "VIRABHADRASANA"
<Y4>:
    Label:
        text: "ANULOM VILOM"
<E1>:
    Label:
        text: "CROSS BAR"
<E2>:
    Label:
        text: "COBRA POSTION"
<E3>:
    Label:
        text: "WIDE ARM PUSH-UP"
<E4>:
    Label:
        text: "PUSH-UP"

